/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Reminder = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
});
export const ContentType = IDL.Variant({
  'bookmark' : IDL.Null,
  'general' : IDL.Null,
});
export const SavedContent = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'contentType' : ContentType,
  'linkTitle' : IDL.Text,
});
export const BusinessCard = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Idea = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createIdea' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createReminder' : IDL.Func([Reminder], [], []),
  'createSavedContent' : IDL.Func([SavedContent], [], []),
  'deleteIdea' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Text], [], []),
  'deleteSavedContent' : IDL.Func([IDL.Text], [], []),
  'getBusinessCard' : IDL.Func([], [IDL.Opt(BusinessCard)], ['query']),
  'getBusinessCardByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessCard)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
  'listSavedContent' : IDL.Func([], [IDL.Vec(SavedContent)], ['query']),
  'readIdea' : IDL.Func([IDL.Text], [IDL.Opt(Idea)], ['query']),
  'readReminder' : IDL.Func([IDL.Text], [IDL.Opt(Reminder)], ['query']),
  'readSavedContent' : IDL.Func([IDL.Text], [IDL.Opt(SavedContent)], ['query']),
  'saveBusinessCard' : IDL.Func([BusinessCard], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIdea' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
  'updateSavedContent' : IDL.Func([IDL.Text, SavedContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reminder = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
  });
  const ContentType = IDL.Variant({
    'bookmark' : IDL.Null,
    'general' : IDL.Null,
  });
  const SavedContent = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'contentType' : ContentType,
    'linkTitle' : IDL.Text,
  });
  const BusinessCard = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Idea = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createIdea' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createReminder' : IDL.Func([Reminder], [], []),
    'createSavedContent' : IDL.Func([SavedContent], [], []),
    'deleteIdea' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Text], [], []),
    'deleteSavedContent' : IDL.Func([IDL.Text], [], []),
    'getBusinessCard' : IDL.Func([], [IDL.Opt(BusinessCard)], ['query']),
    'getBusinessCardByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessCard)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
    'listSavedContent' : IDL.Func([], [IDL.Vec(SavedContent)], ['query']),
    'readIdea' : IDL.Func([IDL.Text], [IDL.Opt(Idea)], ['query']),
    'readReminder' : IDL.Func([IDL.Text], [IDL.Opt(Reminder)], ['query']),
    'readSavedContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SavedContent)],
        ['query'],
      ),
    'saveBusinessCard' : IDL.Func([BusinessCard], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIdea' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
    'updateSavedContent' : IDL.Func([IDL.Text, SavedContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };