/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessCard {
  'bio' : string,
  'title' : string,
  'fullName' : string,
  'email' : string,
  'website' : string,
  'phone' : string,
}
export type ContentType = { 'bookmark' : null } |
  { 'general' : null };
export interface Idea { 'id' : string, 'content' : string, 'createdAt' : Time }
export interface Reminder {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : [] | [Time],
}
export interface SavedContent {
  'id' : string,
  'content' : string,
  'contentType' : ContentType,
  'linkTitle' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createIdea' : ActorMethod<[string, string], undefined>,
  'createReminder' : ActorMethod<[Reminder], undefined>,
  'createSavedContent' : ActorMethod<[SavedContent], undefined>,
  'deleteIdea' : ActorMethod<[string], undefined>,
  'deleteReminder' : ActorMethod<[string], undefined>,
  'deleteSavedContent' : ActorMethod<[string], undefined>,
  'getBusinessCard' : ActorMethod<[], [] | [BusinessCard]>,
  'getBusinessCardByPrincipal' : ActorMethod<[Principal], [] | [BusinessCard]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUpcomingReminders' : ActorMethod<[], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listIdeas' : ActorMethod<[], Array<Idea>>,
  'listSavedContent' : ActorMethod<[], Array<SavedContent>>,
  'readIdea' : ActorMethod<[string], [] | [Idea]>,
  'readReminder' : ActorMethod<[string], [] | [Reminder]>,
  'readSavedContent' : ActorMethod<[string], [] | [SavedContent]>,
  'saveBusinessCard' : ActorMethod<[BusinessCard], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIdea' : ActorMethod<[string, string], undefined>,
  'updateReminder' : ActorMethod<[string, Reminder], undefined>,
  'updateSavedContent' : ActorMethod<[string, SavedContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];